# Generated by Django 4.0.2 on 2022-02-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
