# Generated by Django 4.0.2 on 2022-02-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0004_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='submission',
            name='num_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
