# Generated by Django 4.0.2 on 2022-03-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_rename_num_submissions_submission_num_submissions_in_contest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='num_submissions_in_contest',
            new_name='penalty',
        ),
    ]
