# Generated by Django 4.0.2 on 2022-03-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0007_rename_num_submissions_in_contest_submission_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time_solved_in_contest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='wrong_submissions_in_contest',
            field=models.IntegerField(default=0),
        ),
    ]
