# Generated by Django 4.1.4 on 2022-12-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0009_submission_solved_in_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='correct_answer_choice',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('Blank', 'Blank')], default='A', max_length=5),
        ),
        migrations.AddField(
            model_name='problem',
            name='multiple_choice',
            field=models.BooleanField(default=True),
        ),
    ]
