# Generated by Django 4.1.4 on 2022-12-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0010_problem_correct_answer_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='answer_choice_in_contest',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('Blank', 'Blank')], default='Blank', max_length=5),
        ),
        migrations.AddField(
            model_name='submission',
            name='answer_in_contest',
            field=models.IntegerField(default=0),
        ),
    ]
