# Generated by Django 4.0.2 on 2022-02-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='announcement_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='contest',
            name='end_time_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='contest',
            name='start_time_url',
            field=models.URLField(default=''),
        ),
    ]
