# Generated by Django 4.0.2 on 2022-03-01 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_rename_num_submissions_submission_num_submissions_in_contest'),
        ('contests', '0002_contest_announcement_link_contest_end_time_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemset.problem'),
        ),
    ]
