# Generated by Django 4.0.2 on 2022-03-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_contestproblem_contest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
    ]
