# Generated by Django 4.0.2 on 2022-03-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_registration_time_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='total_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
