# Generated by Django 4.0.2 on 2022-03-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_registration_total_penalty_registration_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
