# Generated by Django 4.0.3 on 2022-04-09 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='time_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
