# Generated by Django 4.0.3 on 2022-04-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_announcement_time_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='has_solutions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='solutions_url',
            field=models.URLField(default=''),
        ),
    ]
