# Generated by Django 4.0.3 on 2022-04-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_contest_has_solutions_contest_solutions_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
