# Generated by Django 4.1.4 on 2022-12-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_delete_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_format',
            field=models.CharField(choices=[('AMC8', 'AMC8'), ('AMC10', 'AMC10'), ('AIME', 'AIME'), ('Semicolon', 'Semicolon')], default='Semicolon', max_length=9),
        ),
    ]
