# Generated by Django 4.1.4 on 2022-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_registration_confirmed_honest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='form_user_submit_solutions',
            field=models.BooleanField(default=False),
        ),
    ]
