# Generated by Django 4.1.4 on 2022-12-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_contest_form_user_submit_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='form_link',
            field=models.URLField(default=''),
        ),
    ]
