# Generated by Django 4.1.4 on 2022-12-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_contest_form_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='total_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
